services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    user: root
    command: npm run start:app
    links:
      - redis
    ports:
      - '13019:13019'
    networks:
      - fixtures-network
    env_file: .env
    environment:
      - REDIS_HOST_NAME=fixtures_redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://fixtures_redis:6379
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - redis

  redis:
    container_name: fixtures_redis
    image: redis:alpine
    restart: unless-stopped
    expose:
      - '6379'
    ports:
      - '6379:6379'
    networks:
      - fixtures-network


volumes:
  redis-data:

networks:
  fixtures-network:
